### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by wwping** [beetlex-io/Bumblebee#92]
2020/12/23 15:11:50
Object reference not set to an instance of an object.
   at BeetleX.TcpSession.InvokeReceiveEvent()
   at BeetleX.Buffers.SslStreamX.SyncData(Action receive)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

beetlex  1.5.1.7
beetlex.fasthttpapi  1.8.2.7
Bumblebee 1.3.6.7

偶然间出现的问题，服务停止运行

**Comment by beetlex-io** [comment]
反编译了这个版本的代码是存在这问题，由于会话释放清空了Server属性引起这个方法写日志错误，建议单独升级Beetlex到最新版本。如果存在兼容问题 尝试升到1.5.1.8已解决这一问题

**Comment by wwping** [comment]
我升级一下试试

**Comment by wwping** [comment]
升级到1.5.1.8之后
![1](https://user-images.githubusercontent.com/10977033/102975208-a72b8900-453a-11eb-8602-c038a4cd7b19.png)

**Comment by wwping** [comment]
如果都升级到最新版本， 一些插件会有兼容问题，也会导致无法运行

**Comment by beetlex-io** [comment]
警告提示，无须关心

**Comment by wwping** [comment]
不是的，虽然提示是警告，但是服务没有正常运行，
![24](https://user-images.githubusercontent.com/10977033/102978510-97627380-453f-11eb-9921-e185f695e694.png)

**Comment by wwping** [comment]
BeetleX 1.5.1.8
BeetleX.FastHttpApi 1.8.2.7
![1](https://user-images.githubusercontent.com/10977033/102980922-3f2d7080-4543-11eb-8cfe-ce9d66473918.png)

BeetleX.FastHttpApi 大于 1.8.2.7版本的话，Bumblebee的一些插件不兼容，Log接口修改了，多了 session参数

**Comment by wwping** [comment]
有没有可能是因为我用的是阿里云的免费证书

**Comment by beetlex-io** [comment]
应该不会是证书问题，如果证书无效用浏览器访问一下会有警告

**Comment by beetlex-io** [comment]
不过这错误已经说明在SSL验证阶段，对方关闭连接了

**Comment by wwping** [comment]
我
BeetleX  BeetleX.FastHttpApi  全都更新到最新版也不行
都是这里报错，导致没有正常response
![1](https://user-images.githubusercontent.com/10977033/102994979-07f59a00-4518-11eb-9710-5b4c3ace3f4a.png)

**Comment by beetlex-io** [comment]
这错误是.net core内部错误ssl验证错误终止了，所以无法继续后面的HTTP通讯的。

**Comment by wwping** [comment]
啊。这.....

**Comment by beetlex-io** [comment]
如果不是通过证书机构的域名访问则认为是不安全访问，默认的client都会直接关闭的，不同语言的client都可以取消这样限制，浏览器访问也会警告只能手动继续访问。

**Comment by wwping** [comment]
那证书应该没问题，.net core内部错误 那这有解决办法吗

**Comment by beetlex-io** [comment]
这种错误应该是client调用配置SSL的问题和服务端关系不大，你可以浏览器访问一下就，如果有警告可以手动点继续访问看结果。

**Comment by beetlex-io** [comment]
效果就像访问https://blog.beetlex.io 一样

**Comment by wwping** [comment]
我是api的，直接浏览器打开的话就是一直 pending   无法访问

**Comment by wwping** [comment]
重装了一下服务器的环境，重新发布了所有的服务，貌似没问题了，等一两天看看有没有问题

**Comment by eddyyuen** [comment]
以前遇到SSL出问题，后来用Nginx转发，一劳永逸
